### ISSUE TITLE
Docker plugin initContainer NoClassDefFoundError: FileSystemAbstraction

### ISSUE THREAD

**Issue by LukeeeeBennett** [neo4j-contrib/osm#6]
I am trying to install osm plugin and load osm data into a db on kube.

I am doing this using an `initContainer`

```
plugins: "[]"
core:
  initContainers:
    - name: "osm"
      image: "gcr.io/project/neo4j-osm:latest"
      volumeMounts:
        - name: "plugins"
          mountPath: "/plugins"
        - name: "neo4j-osm"
          mountPath: "/osm"
  additionalVolumes:
    - name: "neo4j-osm"
      emptyDir: {}
  additionalVolumeMounts:
    - name: "neo4j-osm"
      mountPath: "/osm"
```

the dockerfile is

```
FROM maven:3.6.3-jdk-11

WORKDIR /usr/src/app

RUN git clone https://github.com/neo4j-contrib/osm.git /usr/src/app/osm

COPY data/latest.osm.bz2 /usr/src/app/latest.osm.bz2

COPY scripts/init-osm /usr/src/app/init-osm

CMD ["/usr/src/app/init-osm"]

```

the init-osm script is

```
cp -r /usr/src/app/osm /osm/osm
cd /osm/osm
mvn clean install -DskipTests
mvn dependency:copy-dependencies
cd ../..

cp /osm/osm/target/osm-0.2.3-neo4j-4.1.3-procedures.jar /plugins/osm-0.2.3-neo4j-4.1.3-procedures.jar

cp /usr/src/app/latest.osm.bz2 /osm/data/latest.osm.bz2

java -Xms1280m -Xmx1280m -cp /osm/osm/target/osm-0.2.3-neo4j-4.1.3.jar:target/dependency/* org.neo4j.gis.osm.OSMImportTool --skip-duplicate-nodes --delete --into /var/lib/neo4j/data/databases/neo4j --database latest /osm/data/latest.osm.bz2
```

but the last step fails with a cause of `java.lang.NoClassDefFoundError: org/neo4j/io/fs/FileSystemAbstraction`
